config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users
  root to: 'articles#index'

  resources :articles
  resources :profiles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  has_one_attached :imageobject
  belongs_to :user

  mount_uploader :image, ImageUploader

  def author_name
    user.display_name
  end

  def display_created_at
    I18n.l(created_at, format: :default)
  end
      
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  
  belongs_to :profile
  has_many :articles


  def display_name
    profile&.nickname || email.split('@').first
  end

end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!

  def index
    @articles = Article.all
    
  end
  
  def show
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.artices.build(article_params)
    if @article.save
      redirect_to article_path(@article), notice: '保存できました'
    else
      flash.now[:error] = '保存に失敗しました'
      render :new
    end
  end

  def edit
    @article = current_user.articles.find(params[:id])
  end

  def update
    @articles = current_user.articles.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  def delete
    @articles = current_user.articles.find(params[:id])
    article = Article.find(@arams[:id])
    article.destroy!
    redirect_to root_path, notice: '削除できました'
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController::Base

  private
  def user_params
    params.require(:user).permit(:name)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.haml
.container
  %ul
    - article.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @article, local: true) do |f|
    %div
      = f.label :image, 'サムネイル'
    %div
      = f.file_field :image
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    %div
      = f.submit '保存', class: 'btn-primary'

app/views/articles/index.html.haml
= render 'commons/articles', articles: @articles

app/views/articles/show.html.haml
.article#article-show{data: {article_id: @article.id}}

  %h1.article_title= @article.title
  .article_detail
    = link_to account_path(@article.user) do
      = image_tag @article.user.avatar_image

    %div
      %p= @article.author_name
      %p= @article.display_created_at

  - if user_signed_in? && current_user.exists?(@article)
    .article_detail_actions
      .dropdown
        = image_tag 'actions.svg', class: 'dropbtn'
        .dropdown-content.mini
          = link_to '編集する', edit_article_path(@article)
          = link_to '削除する', article_path(@article), data: { method: 'delete', confirm: '本当に削除してもいいですか？'} 

  .article_content
    = @article.content

app/views/commons/_article.html.haml
%article
  %header
    %p= article.author_name
    %p= article.display_created_at
  = link_to article_path(article) do
    .card
      %h2.card_title
        = article&.title
      .card_detail
%hr

app/views/commons/_articles.html.haml
.container
  %hr
    - @articles.each do |article|
      = render 'commons/article', article: article

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Adstudy
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %body
    %header.header
      .header_logos
        %p.header_pageTitle
          = link_to 'AdStudy', root_path
      - if user_signed_in?
        = link_to '新規作成',new_article_path,class: 'header_newPostButton'
        .dropdown
          - if current_user.avatar?
            = image_tag current_user.avatar, class: 'header_avatar dropbtn'
          - else
            = image_tag 'default-avatar.png', class: 'header_avatar dropbtn'
            -# .dropdown-content
            -#   = link_to 'プロフィール', profile_path
            -#   = link_to 'お気に入り', favorites_path
        = link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete' }, class: 'header_logoutBtn'
      - else
        = link_to 'ログイン', new_user_session_path, class: 'header_loginBtn'
        = link_to '新規登録', new_user_registration_path, class: 'header_registrationBtn'
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield